In [30]:
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [31]:
file_path_base = '/content/drive/MyDrive'

In [32]:
df_acm = pd.read_csv(f'{file_path_base}/Relevant(ACM).csv')
df_ieee = pd.read_csv(f'{file_path_base}/Relevant(IEEE).csv')
df_sd = pd.read_csv(f'{file_path_base}/Relevant(Science_direct).csv')

In [33]:
df = pd.concat([df_acm, df_ieee, df_sd])
df.reset_index()
df.head()

,Key,Item Type,Publication Year,Author,Title,Publication Title,ISBN,ISSN,DOI,Url,...,Programming Language,Version,System,Code,Code Number,Section,Session,Committee,History,Legislative Body
0,PQDEDK4D,conferencePaper,2019,"Krüger, Jacob; Çalıklı, Gül; Berger, Thorsten;...",Effects of explicit feature traceability on pr...,Proceedings of the 2019 27th ACM Joint Meeting...,978-1-4503-5572-8,NaN,10.1145/3338906.3338968,https://dl.acm.org/doi/10.1145/3338906.3338968,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,G9QJXGZU,conferencePaper,2017,"Azadmanesh, Mohammad Reza; Hauswirth, Matthias...",Language-independent information flow tracking...,Proceedings of the 25th International Conferen...,978-1-5386-0535-6,NaN,10.1109/ICPC.2017.5,https://dl.acm.org/doi/10.1109/ICPC.2017.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RXE5GTJF,conferencePaper,2018,"DeLozier, Gregory S.; Decker, Michael J.; Newm...",Leveraging the agile development process for s...,Proceedings of the 26th Conference on Program ...,978-1-4503-5714-2,NaN,10.1145/3196321.3196354,https://dl.acm.org/doi/10.1145/3196321.3196354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GWSCNFHE,conferencePaper,2021,"Michelon, Gabriela K.; Linsbauer, Lukas; Assun...",A Hybrid Feature Location Technique for Re-eng...,Proceedings of the 15th International Working ...,978-1-4503-8824-5,NaN,10.1145/3442391.3442403,https://dl.acm.org/doi/10.1145/3442391.3442403,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,QUPY4AMC,journalArticle,2018,"Razzaq, Abdul; Wasala, Asanka; Exton, Chris; B...",The State of Empirical Evaluation in Static Fe...,ACM Trans. Softw. Eng. Methodol.,NaN,1049-331X,10.1145/3280988,https://dl.acm.org/doi/10.1145/3280988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df.shape

(48, 87)

In [35]:
df.columns

Index(['Key', 'Item Type', 'Publication Year', 'Author', 'Title',
       'Publication Title', 'ISBN', 'ISSN', 'DOI', 'Url', 'Abstract Note',
       'Date', 'Date Added', 'Date Modified', 'Access Date', 'Pages',
       'Num Pages', 'Issue', 'Volume', 'Number Of Volumes',
       'Journal Abbreviation', 'Short Title', 'Series', 'Series Number',
       'Series Text', 'Series Title', 'Publisher', 'Place', 'Language',
       'Rights', 'Type', 'Archive', 'Archive Location', 'Library Catalog',
       'Call Number', 'Extra', 'Notes', 'File Attachments', 'Link Attachments',
       'Manual Tags', 'Automatic Tags', 'Editor', 'Series Editor',
       'Translator', 'Contributor', 'Attorney Agent', 'Book Author',
       'Cast Member', 'Commenter', 'Composer', 'Cosponsor', 'Counsel',
       'Interviewer', 'Producer', 'Recipient', 'Reviewed Author',
       'Scriptwriter', 'Words By', 'Guest', 'Number', 'Edition',
       'Running Time', 'Scale', 'Medium', 'Artwork Size', 'Filing Date',
       'Application Number', 'Assignee', 'Issuing Authority', 'Country',
       'Meeting Name', 'Conference Name', 'Court', 'References', 'Reporter',
       'Legal Status', 'Priority Numbers', 'Programming Language', 'Version',
       'System', 'Code', 'Code Number', 'Section', 'Session', 'Committee',
       'History', 'Legislative Body'],
      dtype='object')

In [36]:
columns = ['Title', 'Author', 'Abstract Note', 'Publication Year', 'Item Type',
       'Publication Title', 'ISBN', 'ISSN', 'DOI', 'Url',
       'Date', 'Pages', 'Volume', 'Publisher','Library Catalog']


result = df[columns]

result['Item Type'] = result['Item Type'].replace({'conferencePaper': 'Conference Paper', 'journalArticle': 'Journal Article'})

result.head()

/tmp/ipykernel_959/1486364787.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['Item Type'] = result['Item Type'].replace({'conferencePaper': 'Conference Paper', 'journalArticle': 'Journal Article'})

,Title,Author,Abstract Note,Publication Year,Item Type,Publication Title,ISBN,ISSN,DOI,Url,Date,Pages,Volume,Publisher,Library Catalog
0,Effects of explicit feature traceability on pr...,"Krüger, Jacob; Çalıklı, Gül; Berger, Thorsten;...",Developers spend a substantial amount of their...,2019,Conference Paper,Proceedings of the 2019 27th ACM Joint Meeting...,978-1-4503-5572-8,NaN,10.1145/3338906.3338968,https://dl.acm.org/doi/10.1145/3338906.3338968,2019-08-12,338–349,NaN,Association for Computing Machinery,ACM Digital Library
1,Language-independent information flow tracking...,"Azadmanesh, Mohammad Reza; Hauswirth, Matthias...",Program comprehension tools are often develope...,2017,Conference Paper,Proceedings of the 25th International Conferen...,978-1-5386-0535-6,NaN,10.1109/ICPC.2017.5,https://dl.acm.org/doi/10.1109/ICPC.2017.5,2017-05-20,346–355,NaN,IEEE Press,ACM Digital Library
2,Leveraging the agile development process for s...,"DeLozier, Gregory S.; Decker, Michael J.; Newm...",A practical approach to feature location using...,2018,Conference Paper,Proceedings of the 26th Conference on Program ...,978-1-4503-5714-2,NaN,10.1145/3196321.3196354,https://dl.acm.org/doi/10.1145/3196321.3196354,2018-05-28,370–379,NaN,Association for Computing Machinery,ACM Digital Library
3,A Hybrid Feature Location Technique for Re-eng...,"Michelon, Gabriela K.; Linsbauer, Lukas; Assun...",Software product lines (SPLs) are known for im...,2021,Conference Paper,Proceedings of the 15th International Working ...,978-1-4503-8824-5,NaN,10.1145/3442391.3442403,https://dl.acm.org/doi/10.1145/3442391.3442403,2021-02-09,1–9,NaN,Association for Computing Machinery,ACM Digital Library
4,The State of Empirical Evaluation in Static Fe...,"Razzaq, Abdul; Wasala, Asanka; Exton, Chris; B...",Feature location (FL) is the task of finding t...,2018,Journal Article,ACM Trans. Softw. Eng. Methodol.,NaN,1049-331X,10.1145/3280988,https://dl.acm.org/doi/10.1145/3280988,2018-12-05,2:1–2:58,28.0,NaN,ACM Digital Library

In [37]:
result['Library Catalog'].loc[~df['Library Catalog'].isin(['ACM Digital Library', 'IEEE Xplore'])] = 'Science Direct'
result['Library Catalog'].value_counts()

/tmp/ipykernel_959/2377235933.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  result['Library Catalog'].loc[~df['Library Catalog'].isin(['ACM Digital Library', 'IEEE Xplore'])] = 'Science Direct'
/tmp/ipykernel_959/2377235933.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['Library Catalog'].loc[~df['Library Catalog'].isin(['ACM Digital Library', 'IEEE Xplore'])] = 'Science Direct'

Library Catalog
Science Direct         20
ACM Digital Library    14
IEEE Xplore            14
Name: count, dtype: int64

In [38]:
result.head()

,Title,Author,Abstract Note,Publication Year,Item Type,Publication Title,ISBN,ISSN,DOI,Url,Date,Pages,Volume,Publisher,Library Catalog
0,Effects of explicit feature traceability on pr...,"Krüger, Jacob; Çalıklı, Gül; Berger, Thorsten;...",Developers spend a substantial amount of their...,2019,Conference Paper,Proceedings of the 2019 27th ACM Joint Meeting...,978-1-4503-5572-8,NaN,10.1145/3338906.3338968,https://dl.acm.org/doi/10.1145/3338906.3338968,2019-08-12,338–349,NaN,Association for Computing Machinery,ACM Digital Library
1,Language-independent information flow tracking...,"Azadmanesh, Mohammad Reza; Hauswirth, Matthias...",Program comprehension tools are often develope...,2017,Conference Paper,Proceedings of the 25th International Conferen...,978-1-5386-0535-6,NaN,10.1109/ICPC.2017.5,https://dl.acm.org/doi/10.1109/ICPC.2017.5,2017-05-20,346–355,NaN,IEEE Press,ACM Digital Library
2,Leveraging the agile development process for s...,"DeLozier, Gregory S.; Decker, Michael J.; Newm...",A practical approach to feature location using...,2018,Conference Paper,Proceedings of the 26th Conference on Program ...,978-1-4503-5714-2,NaN,10.1145/3196321.3196354,https://dl.acm.org/doi/10.1145/3196321.3196354,2018-05-28,370–379,NaN,Association for Computing Machinery,ACM Digital Library
3,A Hybrid Feature Location Technique for Re-eng...,"Michelon, Gabriela K.; Linsbauer, Lukas; Assun...",Software product lines (SPLs) are known for im...,2021,Conference Paper,Proceedings of the 15th International Working ...,978-1-4503-8824-5,NaN,10.1145/3442391.3442403,https://dl.acm.org/doi/10.1145/3442391.3442403,2021-02-09,1–9,NaN,Association for Computing Machinery,ACM Digital Library
4,The State of Empirical Evaluation in Static Fe...,"Razzaq, Abdul; Wasala, Asanka; Exton, Chris; B...",Feature location (FL) is the task of finding t...,2018,Journal Article,ACM Trans. Softw. Eng. Methodol.,NaN,1049-331X,10.1145/3280988,https://dl.acm.org/doi/10.1145/3280988,2018-12-05,2:1–2:58,28.0,NaN,ACM Digital Library

In [39]:
df_acm = result[df['Library Catalog'].isin(['ACM Digital Library'])]
df_ieee = result[df['Library Catalog'].isin(['IEEE Xplore'])]
df_sd = result[~df['Library Catalog'].isin(['ACM Digital Library', 'IEEE Xplore'])]

In [40]:
print(f"{df_acm.shape=} \n{df_ieee.shape=} \n{df_sd.shape=}\nTotal: {df_acm.shape[0]+df_ieee.shape[0]+df_sd.shape[0]}")

df_acm.shape=(14, 15)
df_ieee.shape=(14, 15)
df_sd.shape=(20, 15)
Total: 48

In [41]:
df_acm.to_csv(f"{file_path_base}/acm.csv")
df_ieee.to_csv(f"{file_path_base}/ieee.csv")
df_sd.to_csv(f"{file_path_base}/sd.csv")